create database if not exists hive_edu;

use hive_edu;

CREATE TABLE students (
name STRING,
grade INT,
friends ARRAY<STRING>,
subjects MAP<STRING,FLOAT>,
address STRUCT<dong:STRING, si_do:STRING>
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
COLLECTION ITEMS TERMINATED BY '/'
MAP KEYS TERMINATED BY ':'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
